### ISSUE TITLE
htk_io/vecseq.py 这个文件在哪里？

### ISSUE THREAD

**Issue by baipeng0110** [Lukelluke/MCD-toolkit-polished-useful#3]
你好，我也是测试两个wav的MCD，声学特征是提取自merlin的WORLD声码器，我遇到的也是您这个shape不匹配的问题，我没看懂您改的代码那个地方则怎么处理的，我的项目下并没有htk_io/vecseq.py  这个文件  是要新建吗？新建了怎么执行呢？
希望得到您的回复

**Comment by hhm853610070** [comment]
那个文件就在你安装的htk_io包中啊，不过我改了之后出现了其它问题，就是这里issues中提到的那个越界问题，一直不知道怎么解决，你有遇到吗？

**Comment by baipeng0110** [comment]
您的邮件我已经收到，会尽快回复，谢谢。

**Comment by baipeng0110** [comment]
> 

我就按照你的方式处理的，可以计算MCD值，我就先用这个结果了。
但是也会有一个报错。

processing arctic_a26
MCD = 5.653857 (4484 frames)
warping 4484 frames -> 4484 frames (3 repeated, 3 dropped)

Traceback (most recent call last):
  File "bin/dtw_synth", line 126, in <module>
    main(sys.argv)
  File "bin/dtw_synth", line 118, in main
    synthFullWarped = dtw.warpGeneral(synthFull, synthIndexSeq)
  File "/usr/local/lib/python2.7/dist-packages/mcd/dtw.py", line 160, in warpGeneral
    ysWarped = ys[yIndexSeq]
IndexError: index 2989 is out of bounds for axis 0 with size 2989
